### ISSUE TITLE
怎么在路由上使用

### ISSUE THREAD

**Issue by nature2608** [InvalidCode/young-login#1]
这个配置文件只能在linux上使用吗？要在路由上的话怎么使用？很需要，谢谢。

**Comment by 0x2CA** [comment]
已经更新，-h查看帮助

**Comment by 0x2CA** [comment]
是为Linux开发的，需要shell

**Comment by nature2608** [comment]
谢谢。看到你发的更新了
路由上有shell可以运行
厉害。好佩服

发自我的 iPhone
