### ISSUE TITLE
认证方式变成“天翼校园网”如何改进此项目

### ISSUE THREAD

**Issue by nature2608** [InvalidCode/young-login#3]
![qq 20180418193523](https://user-images.githubusercontent.com/32662472/38929673-afb56eec-433f-11e8-97a4-5f2e7a1f951f.png)
认证方式跟以前大致一样，只是添加了验证码，如何处理这个验证码？

**Comment by 0x2CA** [comment]
这个项目的起源来着我们学校的Mac拨号软件，但是现在我们学校的该软件已经被改的面目全非甚至不能用，所以我也没有试过验证码，但是你可以发发你这个网站我浏览一下

**Comment by nature2608** [comment]
@ChoicePhobiaDisorder 原来我们的是portal页面的，客户端也可以登，所以认证方式是一样的。现在这个“天翼校园网”也是类似，也有客户端，这个页面只能在我锐捷认证后打开，你可以加我qq，我发你客户端和脱机页面。我的qq：260821425

**Comment by 0x2CA** [comment]
我看看，http://125.88.59.131:10001/qs/index_gz.jsp

**Comment by ChoicePhobiaDisorder** [comment]
验证码：
http://125.88.59.131:10001/common/image_code.jsp
验证码采用session储存,浏览器使用cookie储存令牌，
对于这个情况我觉得是可以实现，但是用单纯shel已经不行了，如果要改那么得走phantomjs这个类的模块，但是验证码还是得自己输入，除非再加入验证码识别模块，但是这样已经离最初越来越远了。因为这样还不如直接上这个网页登陆！！
请求只是加了验证码请求
$.ajax({
		type : 'POST',
		url : '/ajax/login',
		cache : false,
		data : "wlanuserip=" + $("#wlanuserip").val() + "&wlanacip=" + $("#wlanacip").val() + "&username=" + username + "&password=" + BASE64.encoder(password) + "&code=" + code,
		dataType : 'json',
		success : function(data, textStatus) {
			if (data.resultCode == "0" || data.resultCode == "13002000" ) {
				$("#login").css('display','none'); 
				$("#success").css('display','block');
				if(remember) {
					setCookie('username',username,'password',password);
				} else {
					cleanCookie('username', 'password');
				}
			} else {
				cleanCookie('username', 'password');
				
				if(data.resultCode == "13018000") {
					alert("已办理一人一号多终端业务的用户，请使用客户端登录");
				} else {
					alert(data.resultInfo);
				}
			}
		}
	});

**Comment by 0x2CA** [comment]
验证码：
`http://125.88.59.131:10001/common/image_code.jsp`
验证码采用session储存,浏览器使用cookie储存令牌，
对于这个情况我觉得是可以实现，但是用单纯shel已经不行了，如果要改那么得走phantomjs这个类的模块，但是验证码还是得自己输入，除非再加入验证码识别模块，但是这样已经离最初越来越远了。因为这样还不如直接上这个网页登陆！！
请求只是加了验证码请求
```
$.ajax({
type : 'POST',
url : '/ajax/login',
cache : false,
data : "wlanuserip=" + $("#wlanuserip").val() + "&wlanacip=" + $("#wlanacip").val() + "&username=" + username + "&password=" + BASE64.encoder(password) + "&code=" + code,
dataType : 'json',
success : function(data, textStatus) {
if (data.resultCode == "0" || data.resultCode == "13002000" ) {
$("#login").css('display','none');
$("#success").css('display','block');
if(remember) {
setCookie('username',username,'password',password);
} else {
cleanCookie('username', 'password');
}
} else {
cleanCookie('username', 'password');

			if(data.resultCode == "13018000") {
				alert("已办理一人一号多终端业务的用户，请使用客户端登录");
			} else {
				alert(data.resultInfo);
			}
		}
	}
});
```

**Comment by nature2608** [comment]
那如果用客户端的验证形式呢？那样是不用验证码的。

**Comment by nature2608** [comment]
[win客户端抓包.zip](https://github.com/ChoicePhobiaDisorder/young-login/files/1935287/win.zip)
第一条post的时候有学校的基本信息，密码加密，但是后面那一大串东西是什么？

**Comment by 0x2CA** [comment]
现在我们学校也平台交接使用校园天翼，但是最近准备毕业就业，所以可能进度会比较慢，如果可以你可以试试提交你的代码

**Comment by nature2608** [comment]
我现在也是在实习准备毕业，不是很懂反编译那些
